FROM python:3.12-slim
WORKDIR /app
RUN pip install --no-cache-dir fastapi uvicorn python-jose
COPY app/main_idp.py main_idp.py
EXPOSE 8081
CMD ["uvicorn", "main_idp:app", "--host", "0.0.0.0", "--port", "8081"]
